<a href="https://colab.research.google.com/github/SAKURA-hub69/-/blob/main/%EF%BC%88%E3%81%88%E3%81%84%E3%81%94%EF%BC%89create_graphs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 各種ライブラリのインストール

In [ ]:
!pip install boto3

Collecting boto3
  Downloading boto3-1.35.24-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.36.0,>=1.35.24 (from boto3)
  Downloading botocore-1.35.24-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.11.0,>=0.10.0 (from boto3)
  Downloading s3transfer-0.10.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/dist-packages (from botocore<1.36.0,>=1.35.24->boto3) (2.8.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.10/dist-packages (from botocore<1.36.0,>=1.35.24->boto3) (2.0.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.36.0,>=1.35.24->boto3) (1.16.0)
Downloading boto3-1.35.24-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.2/139.2 kB 1.9 MB/s eta 0:00:00
Downloading botocore-1.35.24-py3-none-any.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 21.2 MB/s eta 0:00:00
Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Downloading s3transfer-0.10.2-py3-none-any.whl (82 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 3.7 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.35.24 botocore-1.35.24 jmespath-1.0.1 s3transfer-0.10.2

In [ ]:
import pathlib
import json, os
from json.decoder import JSONDecodeError
import pandas as pd
import numpy as np
from tqdm import tqdm
from glob import glob
import boto3

In [ ]:
# @title
!pip install boto3

Requirement already satisfied: boto3 in /usr/local/lib/python3.10/dist-packages (1.35.24)
Requirement already satisfied: botocore<1.36.0,>=1.35.24 in /usr/local/lib/python3.10/dist-packages (from boto3) (1.35.24)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from boto3) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from boto3) (0.10.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/dist-packages (from botocore<1.36.0,>=1.35.24->boto3) (2.8.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.10/dist-packages (from botocore<1.36.0,>=1.35.24->boto3) (2.0.7)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.36.0,>=1.35.24->boto3) (1.16.0)

In [ ]:
# @title
ACCESS_KEY="AKIAR36TGQKDR5LGGOMV"
SECRET_KEY="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"

## Google Driveのマウント

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 試験種入力

In [ ]:
test_csv = input("試験種が記載されたファイル名を入力してください(ex.review_paper_chem.csv)")

試験種が記載されたファイル名を入力してください(ex.review_paper_chem.csv)review_paper_英語.csv

## Arrangementファイルをダウンロードするための関数

In [ ]:
import pathlib
import boto3

s3 = boto3.client('s3', aws_access_key_id=ACCESS_KEY, aws_secret_access_key=SECRET_KEY)
bucket = 'ice.review-paper-staging'

download_dir = pathlib.Path('/content/drive/MyDrive/復習の指針（英語）/グラフ作成/arrangement/download')

# Arrangementファイルをダウンロード
def download_file(objkey: str, filepath):
    s3.download_file(bucket, objkey, str(filepath))
    return filepath

def download_info(exam_code: str):
    filename = f'{exam_code}.json'
    objkey = f'{exam_code}/{filename}'
    filepath = download_dir / filename
    return download_file(objkey, filepath)

## グラフ情報をArrangementファイルに記入

In [ ]:
DAIMON_TOKUTEN

NameError: name 'DAIMON_TOKUTEN' is not defined

In [ ]:
import json, os
from json.decoder import JSONDecodeError
import pandas as pd
import numpy as np
from tqdm import tqdm
from glob import glob

arrangement_dir = '/content/drive/MyDrive/復習の指針（英語）/グラフ作成/arrangement'

#master_file = input("グラフを更新したい試験種のcsvファイル名を.csvまで入力してください")

def get_course(original_df: pd.DataFrame, course_code):
    course_df = original_df.query(f'KOZA_CD == "{course_code}"')
    return course_df.reset_index(drop=True)

def get_kamoku(original_df: pd.DataFrame, kamoku_id):
    kamoku_df = original_df.query(f'KAMOKU_ID == "{kamoku_id}"')
    return kamoku_df.reset_index(drop=True)

def get_year(original_df, year):
    year_df = original_df.query(f'SHIKEN_NENDO == "{year}"')
    return year_df.reset_index(drop=True)

def get_daimon(original_df: pd.DataFrame, daimon):
    daimon_df = original_df.query(f'DAIMON_NUM == "{daimon}"')
    return daimon_df.reset_index(drop=True)

def get_mondai(original_df: pd.DataFrame, mondai):
    mondai_df = original_df.query(f'MONDAI_ID == "{mondai}"')
    return mondai_df.reset_index(drop=True)

def get_data(mondai_df, max_score, diff):
    """ヒストグラムのデータのリストを返す"""
    marks = mondai_df['DAIMON_TOKUTEN']
    c = pd.cut(marks, np.arange(0, max_score+1, diff), right=False)
    ranks = list(marks.groupby(c).count())
    return ranks + [marks.count() - sum(ranks)]

def get_ratio(data):
    """ヒストグラムの割合(%)のリストを返す"""
    s = sum(data)
    return [100 * x / s for x in data]

print('load data')
master = pd.read_csv(f'/content/drive/MyDrive/復習の指針（英語）/グラフ作成/入力csvフォルダ/{test_csv}', dtype=str,encoding="utf-8")
master['DAIMON_NUM'] = master['CODE_NUM'].str[-2:]
koza_cd_list = master['KOZA_CD'].unique().tolist()
df1 = pd.read_csv('/content/drive/MyDrive/復習の指針（英語）/グラフ作成/secure-OPSTTS_T_SEITO_KEKKA20240313.csv', dtype=str, usecols=['ATTEMPT_NO', 'KOZA_CD', 'ENSHU_SET_ID', 'DAIMON_ID', 'DAIMON_TOKUTEN'])
#df2 = pd.read_csv('/content/drive/MyDrive/復習の指針全科目共有/演習データ/2023/OPSTTS_T_SEITO_KEKKA-secure_nendo=202220230313_2.csv', dtype=str, usecols=['ATTEMPT_NO', 'KOZA_CD', 'ENSHU_SET_ID', 'DAIMON_ID', 'DAIMON_TOKUTEN'])
df = df1
df['KAMOKU_ID'] = df['ENSHU_SET_ID'].str[4:6]
df['SHIKEN_NENDO'] = df['ENSHU_SET_ID'].str[-2:]
df['DAIMON_NUM'] = df['DAIMON_ID'].str[-2:]
df["KOZA_CD"] = df["KOZA_CD"].replace("82943","1408")
df["KOZA_CD"] = df["KOZA_CD"].replace("82944","1423")
df_max_score = pd.DataFrame()

# 不備答案を除く
df = df.dropna(subset=['DAIMON_TOKUTEN'])
# 回数=1に絞る
df = df.query('ATTEMPT_NO == "1"')
print('done')

if not os.path.isdir(arrangement_dir):
    os.makedirs(arrangement_dir)

course_dfs = {}
for idx, row in tqdm(master.iterrows()):

    course_code = row['KOZA_CD']

    kamoku_id = row['KAMOKU_ID']
    year = row['NENDO']
    daimon_num = row['DAIMON_NUM']
    if pd.isna(daimon_num):
        details = row['DETAILS'].split(' ')[-1]
        daimon_num = details[1]
    course_df = course_dfs.get(course_code, get_course(df, course_code))

    course_dfs[course_code] = course_df
    kamoku_df = get_kamoku(course_df, kamoku_id)
    year_df = get_year(kamoku_df, year)
    daimon_df = get_daimon(year_df, daimon_num)
    try:
        info_path = download_info(row['CODE_NUM'])

        # 階級の幅を指定する
        daimon_df['DAIMON_TOKUTEN'] = daimon_df['DAIMON_TOKUTEN'].astype(float)
        max_score = int(float(row['HAITEN']))
        diff = max_score // 10
        if max_score < 10:
            diff = 1

        # ヒストグラムを計算
        data = get_data(daimon_df, max_score, diff)
        print('    ', data)
        ratio = get_ratio(data)

        # ヒストグラムデータを保存
        with open(info_path) as f:
            info = json.load(f)
        info['graph_hist'] = ratio
        info['score_stat']['mean'] = daimon_df['DAIMON_TOKUTEN'].dropna().astype(int).mean()
        info['score_stat']['sd'] = daimon_df['DAIMON_TOKUTEN'].astype(int).std()
        info['score_stat']['max'] = max_score
        print('    mean:', info['score_stat']['mean'])
        print('    sd:  ', info['score_stat']['sd'])

        # 柏が追加
        print(year,daimon_num)

        with open(arrangement_dir + '/' + os.path.basename(info_path), 'w') as f:
            json.dump(info, f, indent=4)
    except IndexError:
        continue
    except FileNotFoundError as e:
        print(row['CODE_NUM'])
    except JSONDecodeError as e:
        print(f"JSONDecodeError: {row['CODE_NUM']}")
        continue
    except Exception as e:
        print(f"{e}: {row['CODE_NUM']} ")
        continue

load data
done

0it [00:00, ?it/s]<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
1it [00:01,  1.06s/it]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
2it [00:01,  1.44it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
3it [00:01,  1.68it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
4it [00:02,  1.85it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
5it [00:02,  1.95it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
6it [00:03,  2.01it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
7it [00:03,  2.04it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
8it [00:04,  2.09it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
9it [00:04,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
10it [00:05,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
11it [00:05,  2.26it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
12it [00:06,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
13it [00:06,  2.26it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
14it [00:06,  2.30it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
01 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
15it [00:07,  2.33it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
01 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
16it [00:07,  2.31it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
01 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
17it [00:08,  2.27it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
01 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
18it [00:08,  2.25it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
01 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
19it [00:09,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
01 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
20it [00:09,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
01 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
21it [00:10,  2.01it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
02 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
22it [00:10,  1.83it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
02 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
23it [00:11,  1.70it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
02 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
24it [00:12,  1.65it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
02 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
25it [00:12,  1.60it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
02 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
26it [00:13,  1.59it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
02 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
27it [00:13,  1.74it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
02 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
28it [00:14,  1.85it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
03 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
29it [00:14,  1.93it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
03 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
30it [00:15,  2.01it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
03 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
31it [00:15,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
03 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
32it [00:16,  2.08it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
03 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
33it [00:16,  2.07it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
03 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
34it [00:17,  2.11it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
03 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
35it [00:17,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
04 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
36it [00:18,  2.13it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
04 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
37it [00:18,  2.13it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
04 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
38it [00:19,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
04 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
39it [00:19,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
04 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
40it [00:19,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
04 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
41it [00:20,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
04 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
42it [00:20,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
05 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
43it [00:21,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
05 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
44it [00:21,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
05 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
45it [00:22,  2.18it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
05 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
46it [00:22,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
05 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
47it [00:23,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
05 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
48it [00:23,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
05 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
49it [00:24,  1.94it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
06 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
50it [00:24,  1.81it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
06 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
51it [00:25,  1.47it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
06 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
52it [00:26,  1.51it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
06 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
53it [00:27,  1.51it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
06 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
54it [00:27,  1.67it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
06 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
55it [00:28,  1.82it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
06 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
56it [00:28,  1.95it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
07 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
57it [00:28,  2.06it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
07 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
58it [00:29,  2.04it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
07 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
59it [00:29,  2.07it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
07 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
60it [00:30,  2.09it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
07 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
61it [00:30,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
07 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
62it [00:31,  2.13it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
07 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
63it [00:31,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
08 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
64it [00:32,  2.26it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
08 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
65it [00:32,  2.24it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
08 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
66it [00:32,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
08 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
67it [00:33,  2.17it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
08 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
68it [00:33,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
08 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
69it [00:34,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
08 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
70it [00:34,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
09 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
71it [00:35,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
09 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
72it [00:35,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
09 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
73it [00:36,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
09 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
74it [00:36,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
09 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
75it [00:37,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
09 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
76it [00:37,  1.93it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
09 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
77it [00:38,  1.80it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
10 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
78it [00:39,  1.73it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
10 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
79it [00:39,  1.67it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
10 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
80it [00:40,  1.62it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
10 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
81it [00:41,  1.61it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
10 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
82it [00:41,  1.74it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
10 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
83it [00:41,  1.89it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
10 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
84it [00:42,  1.93it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
85it [00:42,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
86it [00:43,  2.04it/s]

     [0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
87it [00:43,  2.06it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
88it [00:44,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
89it [00:44,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
90it [00:45,  2.13it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
91it [00:45,  2.17it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
11 09

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
92it [00:46,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
12 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
93it [00:46,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
12 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
94it [00:46,  2.25it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
12 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
95it [00:47,  2.24it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
12 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
96it [00:47,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
12 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
97it [00:48,  2.18it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
12 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
98it [00:48,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
12 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
99it [00:49,  2.18it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
13 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
100it [00:49,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
13 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
101it [00:50,  1.87it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
13 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
102it [00:50,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
13 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
103it [00:51,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
13 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
104it [00:52,  1.78it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
13 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
105it [00:52,  1.71it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
13 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
106it [00:53,  1.65it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
107it [00:53,  1.63it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
108it [00:54,  1.61it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
109it [00:55,  1.63it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
110it [00:55,  1.74it/s]

     [0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
111it [00:56,  1.88it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
112it [00:56,  2.00it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
113it [00:56,  2.08it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
114it [00:57,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
115it [00:57,  2.09it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
116it [00:58,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
117it [00:58,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
118it [00:59,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
119it [00:59,  2.06it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
120it [01:00,  2.09it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
121it [01:00,  2.11it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
122it [01:01,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
123it [01:01,  2.25it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
124it [01:02,  2.23it/s]

     [0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
125it [01:02,  2.24it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
126it [01:03,  1.70it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
127it [01:03,  1.73it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
128it [01:04,  1.73it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
129it [01:05,  1.47it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
130it [01:06,  1.48it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
131it [01:06,  1.49it/s]

     [0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
132it [01:07,  1.45it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
133it [01:08,  1.48it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
134it [01:08,  1.48it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
135it [01:09,  1.62it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
136it [01:09,  1.72it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
137it [01:10,  1.87it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
138it [01:10,  1.99it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
139it [01:11,  2.09it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
140it [01:11,  2.09it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
141it [01:11,  2.17it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
142it [01:12,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
143it [01:12,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
144it [01:13,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
145it [01:13,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
146it [01:14,  2.13it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
147it [01:14,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
148it [01:15,  2.17it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
149it [01:15,  2.14it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
150it [01:16,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
151it [01:16,  1.88it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
152it [01:17,  2.00it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
153it [01:17,  2.04it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
154it [01:18,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
155it [01:18,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
'utf-8' codec can't decode byte 0x87 in position 416: invalid start byte: 0201102101

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
156it [01:18,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
157it [01:19,  1.99it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
158it [01:20,  1.85it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
159it [01:20,  1.79it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
160it [01:21,  1.74it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
161it [01:22,  1.65it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 08

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
162it [01:22,  1.62it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
163it [01:23,  1.75it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
164it [01:23,  1.84it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
165it [01:24,  1.90it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
166it [01:24,  2.00it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
167it [01:25,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
168it [01:25,  2.14it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 08

169it [01:25,  2.21it/s]

cannot convert float NaN to integer: 0201102301

170it [01:26,  2.20it/s]

cannot convert float NaN to integer: 0201102302

171it [01:26,  2.26it/s]

cannot convert float NaN to integer: 0201102303

172it [01:27,  2.29it/s]

cannot convert float NaN to integer: 0201102304

173it [01:27,  2.29it/s]

cannot convert float NaN to integer: 0201102306

174it [01:28,  2.30it/s]

cannot convert float NaN to integer: 0201102307

175it [01:28,  2.31it/s]

cannot convert float NaN to integer: 0201102308

176it [01:28,  2.60it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0201102401

177it [01:29,  2.86it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0201102402

178it [01:29,  3.08it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0201102403

179it [01:29,  3.06it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0201102404

180it [01:29,  3.22it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0201102405

181it [01:30,  3.31it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0201102406

182it [01:30,  3.30it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0201102407

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
183it [01:31,  2.61it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
184it [01:31,  2.40it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
185it [01:32,  2.27it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
186it [01:32,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
187it [01:33,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
188it [01:33,  1.80it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
189it [01:34,  1.64it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
190it [01:35,  1.55it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
191it [01:35,  1.52it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
192it [01:36,  1.48it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
193it [01:37,  1.58it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
194it [01:37,  1.68it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
195it [01:38,  1.75it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
196it [01:38,  1.85it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
197it [01:39,  1.92it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
198it [01:39,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
199it [01:40,  1.95it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
200it [01:40,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
201it [01:41,  2.05it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
202it [01:41,  2.08it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
203it [01:42,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
204it [01:42,  1.79it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
205it [01:43,  1.83it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
206it [01:43,  1.83it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
207it [01:44,  1.87it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
208it [01:44,  1.91it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
209it [01:45,  1.95it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
210it [01:45,  1.93it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
211it [01:46,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
212it [01:46,  1.96it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
213it [01:47,  1.78it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
214it [01:48,  1.67it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
215it [01:48,  1.63it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
216it [01:49,  1.59it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
217it [01:50,  1.59it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
218it [01:50,  1.57it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
219it [01:51,  1.67it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 04

220it [01:51,  1.92it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0231102401

221it [01:51,  2.19it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0231102402

222it [01:52,  2.46it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0231102403

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
223it [01:52,  2.28it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
224it [01:53,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
225it [01:53,  2.17it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
226it [01:54,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
227it [01:54,  2.09it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
228it [01:55,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
229it [01:55,  2.07it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
230it [01:56,  2.08it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
231it [01:56,  2.08it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
232it [01:57,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
233it [01:57,  1.99it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
234it [01:58,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
235it [01:58,  2.06it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
236it [01:59,  2.05it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
237it [01:59,  2.01it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
238it [02:00,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
239it [02:00,  2.01it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
240it [02:01,  1.81it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
241it [02:02,  1.69it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
242it [02:02,  1.65it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
243it [02:03,  1.59it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
244it [02:04,  1.55it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
245it [02:04,  1.52it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
246it [02:05,  1.62it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
247it [02:05,  1.74it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
248it [02:06,  1.83it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
249it [02:06,  1.85it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
250it [02:07,  1.90it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
251it [02:07,  1.95it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
252it [02:08,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
253it [02:08,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
254it [02:09,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
255it [02:09,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
256it [02:10,  1.66it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
257it [02:11,  1.72it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
258it [02:11,  1.68it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
259it [02:12,  1.80it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
260it [02:12,  1.83it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
261it [02:13,  1.86it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
262it [02:13,  1.93it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 04

263it [02:13,  2.20it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0235112401

264it [02:14,  2.43it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0235112402

265it [02:14,  2.52it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0235112403

266it [02:15,  2.34it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0235112404

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
267it [02:15,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101401

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
268it [02:16,  1.88it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101402

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
269it [02:17,  1.76it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101403

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
270it [02:17,  1.65it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101404

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
271it [02:18,  1.64it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101501

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
272it [02:19,  1.63it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101502

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
273it [02:19,  1.80it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101503

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
274it [02:19,  1.94it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101504

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
275it [02:20,  2.05it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101601

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
276it [02:20,  2.07it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101602

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
277it [02:21,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101603

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
278it [02:21,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101604

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
279it [02:22,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101701

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
280it [02:22,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101702

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
281it [02:23,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101703

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
282it [02:23,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101704

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
283it [02:23,  2.26it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101801

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
284it [02:24,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101802

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
285it [02:24,  2.18it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101803

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
286it [02:25,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101804

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
287it [02:25,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101901

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
288it [02:26,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101902

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
289it [02:26,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101903

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
290it [02:27,  2.26it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234101904

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
291it [02:27,  2.27it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102001

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
292it [02:27,  2.28it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102002

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
293it [02:28,  2.24it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102003

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
294it [02:28,  2.26it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102004

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
295it [02:29,  2.05it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102101

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
296it [02:30,  1.87it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102102

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
297it [02:30,  1.80it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102103

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
298it [02:31,  1.75it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102104

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
299it [02:31,  1.74it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102201

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
300it [02:32,  1.73it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102202

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
301it [02:32,  1.80it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102203

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
302it [02:33,  1.94it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102204

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
303it [02:33,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102301

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
304it [02:34,  2.11it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102302

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
305it [02:34,  2.17it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102303

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
306it [02:35,  2.25it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102304

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
307it [02:35,  2.29it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102401

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
308it [02:36,  1.95it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102402

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
309it [02:36,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102403

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
310it [02:37,  2.06it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0234102404

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
311it [02:37,  2.04it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
312it [02:38,  2.06it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
313it [02:38,  2.08it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
314it [02:39,  2.05it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
14 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
315it [02:39,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
316it [02:39,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
317it [02:40,  2.18it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
318it [02:40,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
15 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
319it [02:41,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
320it [02:41,  2.11it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
321it [02:42,  2.18it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
322it [02:42,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
323it [02:43,  1.91it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101701

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
324it [02:44,  1.73it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101702

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
325it [02:44,  1.69it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101703

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
326it [02:45,  1.66it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101704

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
327it [02:45,  1.66it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101801

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
328it [02:46,  1.65it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101802

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
329it [02:47,  1.77it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101803

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
330it [02:47,  1.85it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101804

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
331it [02:47,  1.94it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101901

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
332it [02:48,  1.99it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101902

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
333it [02:48,  1.98it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101903

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
334it [02:49,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0337101904

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
335it [02:49,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
336it [02:50,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
337it [02:50,  2.04it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
338it [02:51,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
339it [02:51,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
340it [02:52,  2.05it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
341it [02:52,  2.08it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
342it [02:53,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
343it [02:53,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
344it [02:54,  1.97it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
345it [02:54,  2.00it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
346it [02:55,  2.00it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
347it [02:55,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
348it [02:56,  2.02it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
349it [02:56,  2.01it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 04

350it [02:57,  1.99it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0337102401

351it [02:57,  2.02it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0337102402

352it [02:58,  2.01it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0337102403

353it [02:58,  2.00it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0337102404

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
354it [02:59,  1.86it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101401

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
355it [03:00,  1.79it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101402

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
356it [03:00,  1.73it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101403

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
357it [03:01,  1.77it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101404

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
358it [03:01,  1.87it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101405

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
359it [03:02,  1.96it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101501

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
360it [03:02,  1.77it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101502

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
361it [03:03,  1.88it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101503

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
362it [03:03,  1.98it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101504

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
363it [03:04,  2.04it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
JSONDecodeError: 0236101505

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
364it [03:04,  2.11it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
365it [03:05,  2.15it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
366it [03:05,  2.18it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
367it [03:06,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
16 04

368it [03:06,  2.40it/s]

An error occurred (404) when calling the HeadObject operation: Not Found: 0236101605

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
369it [03:06,  2.35it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
370it [03:07,  2.34it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
371it [03:07,  2.32it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
372it [03:08,  2.29it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
17 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
373it [03:08,  2.27it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
374it [03:09,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
375it [03:09,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
376it [03:09,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
377it [03:10,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
18 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
378it [03:10,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
379it [03:11,  1.98it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
380it [03:12,  1.84it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
381it [03:12,  1.76it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
382it [03:13,  1.65it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
19 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
383it [03:14,  1.63it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
384it [03:14,  1.59it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
385it [03:15,  1.64it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
386it [03:15,  1.77it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
387it [03:16,  1.88it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
20 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
388it [03:16,  1.93it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
389it [03:17,  2.01it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
390it [03:17,  2.03it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
391it [03:18,  2.10it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
392it [03:18,  2.12it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
21 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
393it [03:18,  2.16it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
394it [03:19,  2.11it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
395it [03:19,  2.17it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
396it [03:20,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
397it [03:20,  2.22it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
22 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
398it [03:21,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
399it [03:21,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
400it [03:22,  2.21it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
401it [03:22,  2.19it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
402it [03:23,  2.14it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
23 05

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
403it [03:23,  2.14it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
24 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
404it [03:23,  2.20it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
24 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
405it [03:24,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
24 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
406it [03:24,  2.23it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
24 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
407it [03:25,  1.98it/s]

     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
24 05

In [ ]:
import json, os
from json.decoder import JSONDecodeError
import pandas as pd
import numpy as np
from tqdm import tqdm
from glob import glob

arrangement_dir = '/content/drive/MyDrive/復習の指針（英語）/グラフ作成/arrangement'

#master_file = input("グラフを更新したい試験種のcsvファイル名を.csvまで入力してください")

def get_course(original_df: pd.DataFrame, course_code):
    course_df = original_df.query(f'KOZA_CD == "{course_code}"')
    return course_df.reset_index(drop=True)

def get_kamoku(original_df: pd.DataFrame, kamoku_id):
    kamoku_df = original_df.query(f'KAMOKU_ID == "{kamoku_id}"')
    return kamoku_df.reset_index(drop=True)

def get_year(original_df, year):
    year_df = original_df.query(f'SHIKEN_NENDO == "{year}"')
    return year_df.reset_index(drop=True)

def get_daimon(original_df: pd.DataFrame, daimon):
    daimon_df = original_df.query(f'DAIMON_NUM == "{daimon}"')
    return daimon_df.reset_index(drop=True)

def get_mondai(original_df: pd.DataFrame, mondai):
    mondai_df = original_df.query(f'MONDAI_ID == "{mondai}"')
    return mondai_df.reset_index(drop=True)

def get_data(mondai_df, max_score, diff):
    """ヒストグラムのデータのリストを返す"""
    marks = mondai_df['DAIMON_TOKUTEN']
    c = pd.cut(marks, np.arange(0, max_score+1, diff), right=False)
    ranks = list(marks.groupby(c).count())
    return ranks + [marks.count() - sum(ranks)]

def get_ratio(data):
    """ヒストグラムの割合(%)のリストを返す"""
    s = sum(data)
    return [100 * x / s for x in data]

print('load data')
master = pd.read_csv(f'/content/drive/MyDrive/復習の指針（英語）/グラフ作成/入力csvフォルダ/{test_csv}', dtype=str,encoding="utf-8")
master['DAIMON_NUM'] = master['CODE_NUM'].str[-2:]
koza_cd_list = master['KOZA_CD'].unique().tolist()
df1 = pd.read_csv('/content/drive/MyDrive/復習の指針（英語）/グラフ作成/secure-OPSTTS_T_SEITO_KEKKA20240313.csv', dtype=str, usecols=['ATTEMPT_NO', 'KOZA_CD', 'ENSHU_SET_ID', 'DAIMON_ID', 'DAIMON_TOKUTEN'])
#df2 = pd.read_csv('/content/drive/MyDrive/復習の指針全科目共有/演習データ/2023/OPSTTS_T_SEITO_KEKKA-secure_nendo=202220230313_2.csv', dtype=str, usecols=['ATTEMPT_NO', 'KOZA_CD', 'ENSHU_SET_ID', 'DAIMON_ID', 'DAIMON_TOKUTEN'])
df = df1
df['KAMOKU_ID'] = df['ENSHU_SET_ID'].str[4:6]
df['SHIKEN_NENDO'] = df['ENSHU_SET_ID'].str[-2:]
df['DAIMON_NUM'] = df['DAIMON_ID'].str[-2:]
df["KOZA_CD"] = df["KOZA_CD"].replace("82943","1408")
df["KOZA_CD"] = df["KOZA_CD"].replace("82944","1423")
df_max_score = pd.DataFrame()

# 不備答案を除く
df = df.dropna(subset=['DAIMON_TOKUTEN'])
# 回数=1に絞る
df = df.query('ATTEMPT_NO == "1"')
print('done')

load data
done

In [ ]:
master.iterrows()

In [ ]:
if not os.path.isdir(arrangement_dir):
    os.makedirs(arrangement_dir)

course_dfs = {}
for idx, row in tqdm(master.iterrows()):

    course_code = row['KOZA_CD']

    kamoku_id = row['KAMOKU_ID']
    year = row['NENDO']
    daimon_num = row['DAIMON_NUM']
    if pd.isna(daimon_num):
        details = row['DETAILS'].split(' ')[-1]
        daimon_num = details[1]
    course_df = course_dfs.get(course_code, get_course(df, course_code))

    course_dfs[course_code] = course_df
    kamoku_df = get_kamoku(course_df, kamoku_id)
    year_df = get_year(kamoku_df, year)
    daimon_df = get_daimon(year_df, daimon_num)
    try:
        info_path = download_info(row['CODE_NUM'])

        # 階級の幅を指定する
        daimon_df['DAIMON_TOKUTEN'] = daimon_df['DAIMON_TOKUTEN'].astype(float)
        max_score = int(float(row['HAITEN']))
        diff = max_score // 10
        if max_score < 10:
            diff = 1

        # ヒストグラムを計算
        data = get_data(daimon_df, max_score, diff)
        print('    ', data)
        ratio = get_ratio(data)

        # ヒストグラムデータを保存
        with open(info_path) as f:
            info = json.load(f)
        info['graph_hist'] = ratio
        info['score_stat']['mean'] = daimon_df['DAIMON_TOKUTEN'].dropna().astype(int).mean()
        info['score_stat']['sd'] = daimon_df['DAIMON_TOKUTEN'].astype(int).std()
        info['score_stat']['max'] = max_score
        print('    mean:', info['score_stat']['mean'])
        print('    sd:  ', info['score_stat']['sd'])

        # 柏が追加
        print(year,daimon_num)

        with open(arrangement_dir + '/' + os.path.basename(info_path), 'w') as f:
            json.dump(info, f, indent=4)
    except IndexError:
        continue
    except FileNotFoundError as e:
        print(row['CODE_NUM'])
    except JSONDecodeError as e:
        print(f"JSONDecodeError: {row['CODE_NUM']}")
        continue
    except Exception as e:
        print(f"{e}: {row['CODE_NUM']} ")
        continue

0it [00:00, ?it/s]<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
1it [00:01,  1.21s/it]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
2it [00:01,  1.29it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
3it [00:02,  1.61it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
4it [00:02,  1.81it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
5it [00:03,  1.91it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
6it [00:03,  1.97it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
99 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
7it [00:03,  2.01it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 01

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
8it [00:04,  1.99it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 02

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
9it [00:05,  1.84it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 03

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
10it [00:05,  1.73it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 04

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
11it [00:06,  1.62it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 06

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
12it [00:07,  1.59it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 07

<ipython-input-38-0e57f5ca4232>:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  ranks = list(marks.groupby(c).count())
<ipython-input-38-0e57f5ca4232>:42: RuntimeWarning: invalid value encountered in scalar divide
  return [100 * x / s for x in data]
13it [00:07,  1.58it/s]

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    mean: nan
    sd:   nan
00 08

13it [00:07,  1.63it/s]

KeyboardInterrupt:

In [ ]:
daimon_df

Empty DataFrame
Columns: [KOZA_CD, ENSHU_SET_ID, ATTEMPT_NO, DAIMON_ID, DAIMON_TOKUTEN, KAMOKU_ID, SHIKEN_NENDO, DAIMON_NUM]
Index: []

In [ ]:
df1111 = df[(df["SHIKEN_NENDO"]=="16") & (df["DAIMON_NUM"]=="03") & (df["KAMOKU_ID"]=="10") & (df["KOZA_CD"]=="2632")]

In [ ]:
df1111

,KOZA_CD,ENSHU_SET_ID,ATTEMPT_NO,DAIMON_ID,DAIMON_TOKUTEN,KAMOKU_ID,SHIKEN_NENDO,DAIMON_NUM
9260,2632,26321016,1,1140101011101603,27.0,10,16,03
16666,2632,26321016,1,1140101011101603,29.0,10,16,03
19613,2632,26321016,1,1140101011101603,27.0,10,16,03
31639,2632,26321016,1,1140101011101603,25.0,10,16,03
34994,2632,26321016,1,1140101011101603,29.0,10,16,03
...,...,...,...,...,...,...,...,...
4439488,2632,26321016,1,1140101011101603,16.0,10,16,03
4448596,2632,26321016,1,1140101011101603,25.0,10,16,03
4465976,2632,26321016,1,1140101011101603,23.0,10,16,03
4471152,2632,26321016,1,1140101011101603,16.0,10,16,03
4513942,2632,26321016,1,1140101011101603,35.0,10,16,03

## グラフ作成

In [ ]:
# グラフを作成するためのクラス
import os
import json
import math
import pathlib
import numpy as np
import matplotlib as mpl
from matplotlib import font_manager as fm
import matplotlib.pyplot as plt

mpl.use("pdf")  # for linux


class Graph:
    background_color = "#EAEAEA"
    default_bar_color = "#646464"
    target_bar_color = "#FF0000"
    text_color = "black"
    graph_dir = pathlib.Path("/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/graphs/")
    bar_width = 0.7
    font = fm.FontProperties(fname="/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/fonts/katyoub.ttf", size=18)
    legend_font = fm.FontProperties(fname="/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/fonts/katyoub.ttf", size=22, weight='semibold')


    def __init__(self, exam_code):
        self.exam_code = exam_code
        self.figsize = self.get_figsize()
        info = self.get_info(exam_code)
        max_score = info['score_stat']['max']
        self.data = info['graph_hist']
        self.ranks = self.get_ranks(self.data, max_score)
        self.labels = self.get_labels(self.ranks, max_score)

    def target_graph_create(self, target):
        if target >= len(self.labels):
            raise ValueError("targetNum must be under the label length")

        fig, ax = plt.subplots(facecolor=self.background_color, figsize=self.figsize)
        fig.gca().spines['right'].set_visible(False)
        fig.gca().spines['left'].set_visible(False)
        fig.gca().spines['top'].set_visible(False)
        fig.gca().spines['bottom'].set_linewidth(0.5)
        fig.gca().spines['bottom'].set_color(self.text_color)
        fig.gca().yaxis.set_ticks_position('left')
        fig.gca().xaxis.set_ticks_position('bottom')
        fig.subplots_adjust(left=0.08, right=0.93, top=0.83, bottom=0.1)

        ax.set_facecolor(self.background_color)
        x_ticks = np.arange(len(self.labels))
        y_ticks = self.get_yticks(self.data)
        ax.bar(x_ticks, self.data, width=self.bar_width, color=self.default_bar_color)
        ax.bar(target, self.data[target], width=self.bar_width, color=self.target_bar_color, label="あなたの立ち位置 (%)")
        ax.set_xticks(x_ticks)
        ax.set_xticklabels(self.labels, color=self.text_color, fontproperties=self.font)
        ax.set_yticks(y_ticks)
        ax.set_yticklabels(y_ticks, fontproperties=self.font, color=self.text_color)
        # ax.legend(prop=self.legend_font).get_frame().set_alpha(0.0)
        ax.legend(bbox_to_anchor=(.9, 1.25) ,prop=self.legend_font).get_frame().set_alpha(0.0)

        for i in range(len(self.labels)):
            ax.annotate(f'{self.data[i]:.1f}', xy=(i, self.data[i]), xytext=(0, 0.5), textcoords="offset points",
                        ha='center', va='bottom', color=self.text_color, fontproperties=self.font)

        graph_filepath = self.graph_filepath(target)
        # plt.show()  # テスト描画用
        fig.savefig(graph_filepath, facecolor=fig.get_facecolor())
        plt.close()

    def graph_create(self):
        for target in range(len(self.labels)):
            self.target_graph_create(target)

    @staticmethod
    def get_figsize():
        return [12.0, 4.0]

    @staticmethod
    def get_yticks(data):
        highest = (max(data))
        if highest >= 20.0:
            return np.arange(0, math.ceil(highest + 4), 10)
        elif highest >= 10.0:
            return np.arange(0, math.ceil(highest + 2), 2)
        else:
            return np.arange(0, math.ceil(highest + 1), 1)

    @staticmethod
    def get_ranks(data, max_score):
        diff = max_score // (len(data) - 1)
        return [diff * (i) for i in range(len(data))]

    @staticmethod
    def get_labels(ranks, max_score):
        return [f'{rank}' if rank == max_score else f'{rank}~' for rank in ranks]

    def graph_filepath(self, target):
        filename = self.filename(target)
        if not os.path.isdir(Graph.graph_dir / pathlib.Path(self.exam_code)):
            os.makedirs(Graph.graph_dir / pathlib.Path(self.exam_code))

        return Graph.graph_dir / pathlib.Path(self.exam_code) / pathlib.Path(filename)

    def filename(self, target):
        return f"{self.exam_code}_graph_{self.ranks[target]}.svg"

    @staticmethod
    def get_info(exam_code):
        json_path = f"/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/arrangement/{exam_code}.json"
        with open(json_path, "r", encoding="utf-8") as f:
            return json.load(f)


# テスト描画用
# %matplotlib inline

In [ ]:
import pathlib
from json.decoder import JSONDecodeError
from pathlib import Path
# review_system/fonts/katyoub.ttfをシステムにインストールして~/.matplotlibの*font*というファイルを削除する
directory_path = Path('/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/arrangement')
arrangement_file_names = [file.name for file in directory_path.iterdir() if file.is_file()]
master_file_names_1 = master['CODE_NUM'].unique().tolist()
master_file_names_2 = []
for i in master_file_names_1:
  j = i + ".json"
  master_file_names_2.append(j)
common_file_names = sorted(list(set(master_file_names_2)&set(arrangement_file_names)))
print(common_file_names)
#for filename in sorted(pathlib.Path('/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/arrangement').glob('*.json')):
for filename in common_file_names:
    filename = filename[:-5]
    print(filename)
    try:
        g = Graph(filename)
        g.graph_create()
    except KeyError:
        continue
    except JSONDecodeError:
        print(f'JSONDecodeError: {filename}')
        continue
    except Exception as e:
        print(f'{filename}: {e}')

['0233201401.json', '0233201402.json', '0233201403.json', '0233201404.json', '0233201501.json', '0233201502.json', '0233201503.json', '0233201504.json', '0233201601.json', '0233201602.json', '0233201603.json', '0233201604.json', '0233201701.json', '0233201702.json', '0233201703.json', '0233201704.json', '0233201801.json', '0233201802.json', '0233201803.json', '0233201804.json', '0233201901.json', '0233201902.json', '0233201903.json', '0233201904.json', '0233202001.json', '0233202002.json', '0233202003.json', '0233202004.json', '0233202101.json', '0233202102.json', '0233202103.json', '0233202104.json', '0233202201.json', '0233202202.json', '0233202203.json', '0233202204.json', '0233202301.json', '0233202302.json', '0233202303.json', '0233202304.json', '0234201401.json', '0234201402.json', '0234201403.json', '0234201501.json', '0234201502.json', '0234201503.json', '0234201601.json', '0234201602.json', '0234201603.json', '0234201701.json', '0234201702.json', '0234201703.json', '0234201801.json', '0234201802.json', '0234201803.json', '0234201901.json', '0234201902.json', '0234201903.json', '0234202001.json', '0234202002.json', '0234202003.json', '0234212101.json', '0234212102.json', '0234212103.json', '0234212201.json', '0234212202.json', '0234212203.json', '0234212301.json', '0234212302.json', '0234212303.json', '0234222101.json', '0234222201.json', '0234222301.json', '0236211401.json', '0236211402.json', '0236211403.json', '0236211404.json', '0236211501.json', '0236211502.json', '0236211503.json', '0236211504.json', '0236211601.json', '0236211602.json', '0236211603.json', '0236211604.json', '0236211701.json', '0236211702.json', '0236211703.json', '0236211704.json', '0236211801.json', '0236211802.json', '0236211803.json', '0236211804.json', '0236211901.json', '0236211902.json', '0236211903.json', '0236211904.json', '0236212001.json', '0236212002.json', '0236212003.json', '0236212004.json', '0236212101.json', '0236212102.json', '0236212103.json', '0236212104.json', '0236212201.json', '0236212202.json', '0236212203.json', '0236212204.json', '0236212301.json', '0236212302.json', '0236212303.json', '0236212304.json', '0236221401.json', '0236221402.json', '0236221403.json', '0236221404.json', '0236221501.json', '0236221502.json', '0236221503.json', '0236221504.json', '0236221601.json', '0236221602.json', '0236221603.json', '0236221604.json', '0236221701.json', '0236221702.json', '0236221703.json', '0236221704.json', '0236221801.json', '0236221802.json', '0236221803.json', '0236221804.json', '0236221901.json', '0236221902.json', '0236221903.json', '0236221904.json', '0236222001.json', '0236222002.json', '0236222003.json', '0236222004.json', '0236222101.json', '0236222102.json', '0236222103.json', '0236222104.json', '0236222201.json', '0236222202.json', '0236222203.json', '0236222204.json', '0236222301.json', '0236222302.json', '0236222303.json', '0236222304.json', '0238202301.json', '0238202302.json', '0238202303.json', '0238211401.json', '0238211402.json', '0238211403.json', '0238211501.json', '0238211502.json', '0238211503.json', '0238211601.json', '0238211602.json', '0238211603.json', '0238211701.json', '0238211702.json', '0238211703.json', '0238211801.json', '0238211802.json', '0238211803.json', '0238211901.json', '0238211902.json', '0238211903.json', '0238212001.json', '0238212002.json', '0238212003.json', '0238212101.json', '0238212102.json', '0238212103.json', '0238212201.json', '0238212202.json', '0238212203.json', '0238221401.json', '0238221402.json', '0238221403.json', '0238221404.json', '0238221405.json', '0238221501.json', '0238221502.json', '0238221503.json', '0238221504.json', '0238221505.json', '0238221601.json', '0238221602.json', '0238221603.json', '0238221604.json', '0238221605.json', '0238221701.json', '0238221702.json', '0238221703.json', '0238221704.json', '0238221705.json', '0238221801.json', '0238221802.json', '0238221803.json', '0238221804.json', '0238221805.json', '0238221901.json', '0238221902.json', '0238221903.json', '0238221904.json', '0238222001.json', '0238222002.json', '0238222101.json', '0238222102.json', '0238222201.json', '0238222202.json', '0239201401.json', '0239201402.json', '0239201403.json', '0239201404.json', '0239201501.json', '0239201502.json', '0239201503.json', '0239201504.json', '0239201601.json', '0239201602.json', '0239201603.json', '0239201604.json', '0239201701.json', '0239201702.json', '0239201703.json', '0239201704.json', '0239201801.json', '0239201802.json', '0239201803.json', '0239201804.json', '0239201901.json', '0239201902.json', '0239201903.json', '0239201904.json', '0239202001.json', '0239202002.json', '0239202003.json', '0239202004.json', '0239202101.json', '0239202102.json', '0239202103.json', '0239202104.json', '0239202201.json', '0239202202.json', '0239202203.json', '0239202204.json', '0239202301.json', '0239202302.json', '0239202303.json', '0239202304.json']
0233201401
0233201402
0233201403
0233201404
0233201501
0233201502
0233201503
0233201504
0233201601
0233201602
0233201603
0233201604
0233201701
0233201702
0233201703
0233201704
0233201801
0233201802
0233201803
0233201804
0233201901
0233201902
0233201903
0233201904
0233202001
0233202002
0233202003
0233202004
0233202101
0233202102
0233202103
0233202104
0233202201
0233202202
0233202203
0233202204
0233202301
0233202302
0233202303
0233202304
0234201401
0234201402
0234201403
0234201501
0234201502
0234201503
0234201601
0234201602
0234201603
0234201701
0234201702
0234201703
0234201801
0234201802
0234201803
0234201901
0234201902
0234201903
0234202001
0234202002
0234202003
0234212101
0234212102
0234212103
0234212201
0234212202
0234212203
0234212301
0234212302
0234212303
0234222101
0234222201
0234222301
0236211401
0236211402
0236211403
0236211404
0236211501
0236211502
0236211503
0236211504
0236211601
0236211602
0236211603
0236211604
0236211701
0236211702
0236211703
0236211704
0236211801
0236211802
0236211803
0236211804
0236211901
0236211902
0236211903
0236211904
0236212001
0236212002
0236212003
0236212004
0236212101
0236212102
0236212103
0236212104
0236212201
0236212202
0236212203
0236212204
0236212301
0236212302
0236212303
0236212304
0236221401
0236221402
0236221403
0236221404
0236221501
0236221502
0236221503
0236221504
0236221601
0236221602
0236221603
0236221604
0236221701
0236221702
0236221703
0236221704
0236221801
0236221802
0236221803
0236221804
0236221901
0236221902
0236221903
0236221904
0236222001
0236222002
0236222003
0236222004
0236222101
0236222102
0236222103
0236222104
0236222201
0236222202
0236222203
0236222204
0236222301
0236222302
0236222303
0236222304
0238202301
0238202302
0238202303
0238211401
0238211402
0238211403
0238211501
0238211502
0238211503
0238211601
0238211602
0238211603
0238211701
0238211702
0238211703
0238211801
0238211802
0238211803
0238211901
0238211902
0238211903
0238212001
0238212002
0238212003
0238212101
0238212102
0238212103
0238212201
0238212202
0238212203
0238221401
0238221402
0238221403
0238221404
0238221405
0238221501
0238221502
0238221503
0238221504
0238221505
0238221601
0238221602
0238221603
0238221604
0238221605
0238221701
0238221702
0238221703
0238221704
0238221705
0238221801
0238221802
0238221803
0238221804
0238221805
0238221901
0238221902
0238221903
0238221904
0238222001
0238222002
0238222101
0238222102
0238222201
0238222201: cannot convert float NaN to integer
0238222202
0238222202: cannot convert float NaN to integer
0239201401
0239201402
0239201403
0239201404
0239201501
0239201502
0239201503
0239201504
0239201601
0239201602
0239201603
0239201604
0239201701
0239201702
0239201703
0239201704
0239201801
0239201802
0239201803
0239201804
0239201901
0239201902
0239201903
0239201904
0239202001
0239202002
0239202003
0239202004
0239202101
0239202102
0239202103
0239202104
0239202201
0239202202
0239202203
0239202204
0239202301
0239202302
0239202303
0239202304

## AWSにアップロード

In [ ]:
upload_master = pd.read_csv(f'/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/入力csvフォルダ/{test_csv}', dtype=str,encoding="utf-8")
target_code = upload_master["CODE_NUM"].tolist()
print('target code list')
print(target_code)
arrangement_path_list = list(pathlib.Path('/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/arrangement').glob('*.json'))
arrangement_list = []

for a_path in arrangement_path_list:
    arrangement_list.append(a_path.stem)

print('arrangement list')
print(arrangement_list)
common_list = sorted(list(set(target_code) & set(arrangement_list)))
print(common_list)

for code_num in common_list:
    print(code_num)
    s3.upload_file((f'/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/arrangement/{code_num}.json'), bucket, f'{code_num}/{code_num}.json')

    for graph_file in sorted(pathlib.Path(f'/content/drive/MyDrive/復習の指針全科目共有/グラフ作成/graphs/{code_num}').glob('*.svg')):
        s3.upload_file(str(graph_file), bucket, f'{code_num}/{graph_file.name}')

target code list
['0233201401', '0233201402', '0233201403', '0233201404', '0233201501', '0233201502', '0233201503', '0233201504', '0233201601', '0233201602', '0233201603', '0233201604', '0233201701', '0233201702', '0233201703', '0233201704', '0233201801', '0233201802', '0233201803', '0233201804', '0233201901', '0233201902', '0233201903', '0233201904', '0233202001', '0233202002', '0233202003', '0233202004', '0233202101', '0233202102', '0233202103', '0233202104', '0233202201', '0233202202', '0233202203', '0233202204', '0233202301', '0233202302', '0233202303', '0233202304', '0234201401', '0234201402', '0234201403', '0234201501', '0234201502', '0234201503', '0234201601', '0234201602', '0234201603', '0234201701', '0234201702', '0234201703', '0234201801', '0234201802', '0234201803', '0234201901', '0234201902', '0234201903', '0234202001', '0234202002', '0234202003', '0234212101', '0234212102', '0234212103', '0234222101', '0234212201', '0234212202', '0234212203', '0234222201', '0234212301', '0234212302', '0234212303', '0234222301', '0236211401', '0236211402', '0236211403', '0236211404', '0236221401', '0236221402', '0236221403', '0236221404', '0236211501', '0236211502', '0236211503', '0236211504', '0236221501', '0236221502', '0236221503', '0236221504', '0236211601', '0236211602', '0236211603', '0236211604', '0236221601', '0236221602', '0236221603', '0236221604', '0236211701', '0236211702', '0236211703', '0236211704', '0236221701', '0236221702', '0236221703', '0236221704', '0236211801', '0236211802', '0236211803', '0236211804', '0236221801', '0236221802', '0236221803', '0236221804', '0236211901', '0236211902', '0236211903', '0236211904', '0236221901', '0236221902', '0236221903', '0236221904', '0236212001', '0236212002', '0236212003', '0236212004', '0236222001', '0236222002', '0236222003', '0236222004', '0236212101', '0236212102', '0236212103', '0236212104', '0236222101', '0236222102', '0236222103', '0236222104', '0236212201', '0236212202', '0236212203', '0236212204', '0236222201', '0236222202', '0236222203', '0236222204', '0236212301', '0236212302', '0236212303', '0236212304', '0236222301', '0236222302', '0236222303', '0236222304', '0239201401', '0239201402', '0239201403', '0239201404', '0239201501', '0239201502', '0239201503', '0239201504', '0239201601', '0239201602', '0239201603', '0239201604', '0239201701', '0239201702', '0239201703', '0239201704', '0239201801', '0239201802', '0239201803', '0239201804', '0239201901', '0239201902', '0239201903', '0239201904', '0239202001', '0239202002', '0239202003', '0239202004', '0239202101', '0239202102', '0239202103', '0239202104', '0239202201', '0239202202', '0239202203', '0239202204', '0239202301', '0239202302', '0239202303', '0239202304', '0238211401', '0238211402', '0238211403', '0238221401', '0238221402', '0238221403', '0238221404', '0238221405', '0238211501', '0238211502', '0238211503', '0238221501', '0238221502', '0238221503', '0238221504', '0238221505', '0238211601', '0238211602', '0238211603', '0238221601', '0238221602', '0238221603', '0238221604', '0238221605', '0238211701', '0238211702', '0238211703', '0238221701', '0238221702', '0238221703', '0238221704', '0238221705', '0238211801', '0238211802', '0238211803', '0238221801', '0238221802', '0238221803', '0238221804', '0238221805', '0238211901', '0238211902', '0238211903', '0238221901', '0238221902', '0238221903', '0238221904', '0238212001', '0238212002', '0238212003', '0238222001', '0238222002', '0238212101', '0238212102', '0238212103', '0238222101', '0238222102', '0238212201', '0238212202', '0238212203', '0238222201', '0238222202', '0238202301', '0238202302', '0238202303']
arrangement list

ここより下のプログラムは回さないでください

upload start
0201100001
0201100002
0201100003
0201100004
0201100006
0201100007
0201100008
0201100101
0201100102
0201100103
0201100104
0201100106
0201100107
0201100108
0201100201
0201100202
0201100203
0201100204
0201100206
0201100207
0201100208
0201100301
0201100302
0201100303
0201100304
0201100306
0201100307
0201100308
0201100401
0201100402
0201100403
0201100404
0201100406
0201100407
0201100408
0201100501
0201100502
0201100503
0201100504
0201100506
0201100507
0201100508
0201100601
0201100602
0201100603
0201100604
0201100606
0201100607
0201100608
0201100701
0201100702
0201100703
0201100704
0201100706
0201100707
0201100708
0201100801
0201100802
0201100803
0201100804
0201100806
0201100807
0201100808
0201100901
0201100902
0201100903
0201100904
0201100906
0201100907
0201100908
0201101001
0201101002
0201101003
0201101004
0201101006
0201101007
0201101008
0201101101
0201101102
0201101103
0201101104
0201101105
0201101107
0201101108
0201101109
0201101201
0201101202
0201101203
0201101204
0201101206
0201101207
0201101208
0201101301
0201101302
0201101303
0201101304
0201101306
0201101307
0201101308
0201101401
0201101402
0201101403
0201101404
0201101406
0201101407
0201101408
0201101501
0201101502
0201101503
0201101504
0201101506
0201101507
0201101508
0201101601
0201101602
0201101603
0201101604
0201101606
0201101607
0201101608
0201101701
0201101702
0201101703
0201101704
0201101706
0201101707
0201101708
0201101801
0201101802
0201101803
0201101804
0201101806
0201101807
0201101808
0201101901
0201101902
0201101903
0201101904
0201101906
0201101907
0201101908
0201102001
0201102002
0201102003
0201102004
0201102006
0201102007
0201102008
0201102101
0201102102
0201102103
0201102104
0201102106
0201102107
0201102108
0201102201
0201102202
0201102203
0201102204
0201102206
0201102207
0201102208
0201109901
0201109902
0201109903
0201109904
0201109906
0201109907
0201200001
0201200002
0201200003
0201200004
0201200101
0201200102
0201200103
0201200104
0201200201
0201200301
0201200302
0201200303
0201200304
0201200401
0201200402
0201200403
0201200404
0201200501
0201200502
0201200503
0201200504
0201200601
0201200602
0201200603
0201200604
0201200701
0201200702
0201200703
0201200704
0201200801
0201200802
0201200803
0201200804
0201200901
0201201001
0201201002
0201201003
0201201004
0201201101
0201201201
0201201202
0201201203
0201201204
0201201301
0201201302
0201201303
0201201304
0201201401
0201201402
0201201403
0201201404
0201201501
0201201502
0201201503
0201201504
0201201601
0201201602
0201201603
0201201604
0201201701
0201201801
0201201802
0201201803
0201201804
0201201901
0201202001
0201202002
0201202003
0201202004
0201202101
0201202102
0201202103
0201202104
0201202201
0201300001
0201300002
0201300003
0201300004
0201300101
0201300102
0201300103
0201300104
0201300201
0201300202
0201300203
0201300204
0201300301
0201300302
0201300303
0201300304
0201300401
0201300402
0201300403
0201300404
0201300501
0201300502
0201300503
0201300504
0201300601
0201300602
0201300603
0201300604
0201300701
0201300702
0201300703
0201300704
0201300801
0201300802
0201300803
0201300804
0201300901
0201300902
0201300903
0201300904
0201301001
0201301002
0201301003
0201301004
0201301101
0201301102
0201301103
0201301104
0201301201
0201301202
0201301203
0201301204
0201301301
0201301302
0201301303
0201301304
0201301401
0201301402
0201301403
0201301404
0201301501
0201301502
0201301503
0201301504
0201301601
0201301602
0201301603
0201301604
0201301701
0201301702
0201301703
0201301704
0201301801
0201301802
0201301803
0201301804
0201301901
0201301902
0201301903
0201301904
0201302001
0201302002
0201302003
0201302004
0201302101
0201302102
0201302103
0201302104
0201302201
0201302202
0201302203
0201302204
0201309901
0201309902
0201309903
0201309904
0201400001
0201400002
0201400003
0201400004
0201400005
0201400101
0201400102
0201400103
0201400104
0201400105
0201400201
0201400202
0201400203
0201400301
0201400302
0201400303
0201400304
0201400401
0201400402
0201400403
0201400404
0201400405
0201400501
0201400502
0201400503
0201400504
0201400505
0201400601
0201400602
0201400603
0201400702
0201400703
0201400704
0201400705
0201400801
0201400802
0201400803
0201400804
0201400805
0201400901
0201400902
0201400903
0201401001
0201401002
0201401003
0201401004
0201401005
0201401101
0201401102
0201401103
0201401104
0201401105
0201401201
0201401202
0201401203
0201401301
0201401302
0201401303
0201401304
0201401305
0201401401
0201401402
0201401403
0201401404
0201401405
0201401501
0201401502
0201401503
0201401504
0201401505
0201401601
0201401602
0201401603
0201401604
0201401605
0201401701
0201401702
0201401703
0201401704
0201401705
0201401801
0201401802
0201401803
0201401804
0201401805
0201401901
0201401902
0201401903
0201402001
0201402002
0201402003
0201402004
0201402005
0201402101
0201402102
0201402103
0201402104
0201402105
0201402201
0201402202
0201402203
0201402204
0201402205
0201409901
0201409902
0201409903
0201409904
0201409905
0201421301
0201421302
0201421303
0201421304
0201421401
0201421402
0201421403
0201421404
0201421501
0201421502
0201421503
0201421504
0201421601
0201421602
0201421603
0201421604
0201421605
0201421701
0201421702
0201421703
0201421704
0201421801
0201421802
0201421803
0201421804
0201421901
0201421902
0201421903
0201421904
0201422001
0201422002
0201422003
0201422004
0201422101
0201422102
0201422103
0201422104
0201422201
0201422202
0201422203
0201422204
0201431301
0201431302
0201431303
0201431304
0201431305
0201431306
0201431307
0201431401
0201431402
0201431403
0201431404
0201431405
0201431406
0201431501
0201431502
0201431503
0201431504
0201431505
0201431506
0201431507
0201431601
0201431602
0201431603
0201431604
0201431605
0201431606
0201431607
0201431701
0201431702
0201431703
0201431704
0201431705
0201431706
0201431801
0201431802
0201431803
0201431804
0201431805
0201431806
0201431807
0201431901
0201431902
0201431903
0201432001
0201432002
0201432003
0201432004
0201432005
0201432006
0201432101
0201432102
0201432103
0201432104
0201432105
0201432106
0201432201
0201432202
0201432203
0201432204
0201432205
0201432206
0202200001
0202200002
0202200003
0202200101
0202200201
0202200301
0202200401
0202200402
0202200403
0202200501
0202200502
0202200503
0202200601
0202200602
0202200603
0202200701
0202200801
0202200802
0202200803
0202200901
0202201001
0202201002
0202201003
0202201101
0202201102
0202201103
0202201201
0202201202
0202201203
0202201301
0202201401
0202201402
0202201403
0202201501
0202201502
0202201503
0202201601
0202201602
0202201603
0202201701
0202201801
0202201802
0202201803
0202201901
0202201902
0202201903
0202202001
0202202002
0202202003
0202202101
0202202201
0202202202
0202202203
0202300001
0202300002
0202300003
0202300004
0202300005
0202300006
0202300101
0202300102
0202300103
0202300104
0202300105
0202300106
0202300201
0202300202
0202300203
0202300204
0202300205
0202300206
0202300301
0202300302
0202300303
0202300304
0202300305
0202300306
0202300401
0202300402
0202300403
0202300404
0202300405
0202300406
0202300501
0202300502
0202300503
0202300504
0202300505
0202300506
0202300601
0202300602
0202300603
0202300604
0202300605
0202300606
0202300701
0202300702
0202300703
0202300704
0202300705
0202300706
0202300801
0202300802
0202300803
0202300804
0202300805
0202300806
0202300901
0202300902
0202300903
0202300904
0202300905
0202300906
0202301001
0202301002
0202301003
0202301005
0202301006
0202301101
0202301102
0202301103
0202301104
0202301105
0202301106
0202301201
0202301202
0202301203
0202301204
0202301301
0202301302
0202301303
0202301304
0202301305
0202301306
0202301401
0202301402
0202301403
0202301404
0202301405
0202301406
0202301501
0202301502
0202301503
0202301504
0202301505
0202301506
0202301601
0202301602
0202301603
0202301604
0202301605
0202301606
0202301701
0202301702
0202301703
0202301704
0202301705
0202301706
0202301801
0202301802
0202301803
0202301804
0202301805
0202301806
0202301901
0202301902
0202301903
0202301904